### ISSUE TITLE
[Test] Mongoose 및 Repository 관련 테스트 작성

### ISSUE THREAD

**Issue by PMtHk** [PMtHk/gorosey-lol#16]
## Description

Mongoose를 이용한 데이터베이스 연결 및 데이터베이스 관련 동작 테스트 작성

## Todos

- [ ] ~~Mongoose 연결 관련 테스트 작성~~
- [x] ChannelRepository 테스트 작성
- [x] MatchHistoryRepository 테스트 작성
- [x] RankStatRepository 테스트 작성
- [x] SummonerRepository 테스트 작성
